### ISSUE TITLE
Line and Trafo results

### ISSUE THREAD

**Issue by haugsethFredrik** [Hofsmo/power-system-reliability-examples#1]
To extract the Line & Trafo results, use .index instead of .bus.values:

`line_results=pd.DataFrame(columns=pd.MultiIndex.from_product([net.line.index, ["p_from_mw"]]), index=np.arange(0, iterations), data=0) `

`trafo_results=pd.DataFrame(columns=pd.MultiIndex.from_product([net.trafo.index, ["p_hv_mw"]]), index=np.arange(0, iterations), data=0)`

**Comment by Hofsmo** [comment]
In my notebook the old way works without any problem. Can you describe the problem?

**Comment by Hofsmo** [comment]
It seems to be working.
